### ISSUE TITLE
NMS GUI can't login after the orc8r installation done

### ISSUE THREAD

**Issue by AungKyawOo000** [caprivm/everis_docs#2]
User create show success, but can't login in gui, 

root@magma:~/magma_v1.6/nms/app/packages/magmalte# ./scripts/dev_setup.sh
yarn run v1.22.5
$ node -r @fbcnms/babel-register scripts/migrate.js
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Ran migrations successfully
Done in 12.49s.
yarn run v1.22.5
$ node -rhttps://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax '@fbcnms/babel-register' scripts/setPassword.js magma-test admin@magma.test password1234
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Creating a new user: email=admin@magma.test, password=password1234
Success
Done in 1.58s.
yarn run v1.22.5
$ node -r '@fbcnms/babel-register' scripts/setPassword.js master admin@magma.test password1234
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Creating a new user: email=admin@magma.test, password=password1234
Success
Done in 1.55s.

**Comment by caprivm** [comment]
Hi @AungKyawOo000 , could you tell me please, what is the URL you are using to access the GUI? Remember that it is necessary to access as `https://fb-test` due to the certificate

**Comment by AungKyawOo000** [comment]
Hi caprivm,

I login to NMS GUI with https://magma-test/ , in /etc/host I have put dns for the ip in my window pc. 

But fail to login, from swigger I checked, it don't show the NMS user I have created from cli, it seem fail to create NMS user 

every time.
